### ISSUE TITLE
zap  磁盘报错

### ISSUE THREAD

**Issue by lianqf** [Statemood/documents#1]
[root@k8s160041 ceph-install]# ceph-deploy disk zap cph160046 sdc sdd
[ceph_deploy.conf][DEBUG ] found configuration file at: /root/.cephdeploy.conf
[ceph_deploy.cli][INFO  ] Invoked (2.0.0): /usr/bin/ceph-deploy disk zap cph160046 sdc sdd
[ceph_deploy.cli][INFO  ] ceph-deploy options:
[ceph_deploy.cli][INFO  ]  username                      : None
[ceph_deploy.cli][INFO  ]  verbose                       : False
[ceph_deploy.cli][INFO  ]  overwrite_conf                : False
[ceph_deploy.cli][INFO  ]  subcommand                    : zap
[ceph_deploy.cli][INFO  ]  quiet                         : False
[ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x1b7b8c0>
[ceph_deploy.cli][INFO  ]  cluster                       : ceph
[ceph_deploy.cli][INFO  ]  host                          : cph160046
[ceph_deploy.cli][INFO  ]  func                          : <function disk at 0x1b651b8>
[ceph_deploy.cli][INFO  ]  ceph_conf                     : None
[ceph_deploy.cli][INFO  ]  default_release               : False
[ceph_deploy.cli][INFO  ]  disk                          : ['sdc', 'sdd']
[ceph_deploy.osd][DEBUG ] zapping sdc on cph160046
[cph160046][DEBUG ] connected to host: cph160046 
[cph160046][DEBUG ] detect platform information from remote host
[cph160046][DEBUG ] detect machine type
[cph160046][DEBUG ] find the location of an executable
[ceph_deploy.osd][INFO  ] Distro info: CentOS Linux 7.4.1708 Core
**[cph160046][DEBUG ] zeroing last few blocks of device
[cph160046][DEBUG ] find the location of an executable
[ceph_deploy][ERROR ] Traceback (most recent call last):
[ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/util/decorators.py", line 69, in newfunc
[ceph_deploy][ERROR ]     return f(*a, **kw)
[ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/cli.py", line 164, in _main
[ceph_deploy][ERROR ]     return args.func(args)
[ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/osd.py", line 438, in disk
[ceph_deploy][ERROR ]     disk_zap(args)
[ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/osd.py", line 336, in disk_zap
[ceph_deploy][ERROR ]     if args.debug:
[ceph_deploy][ERROR ] AttributeError: 'Namespace' object has no attribute 'debug'
[ceph_deploy][ERROR ]**

**Comment by Statemood** [comment]
这个是ceph-deploy 的一个bug, 详情 http://tracker.ceph.com/issues/22871.

可以按照 https://github.com/Statemood/documents/tree/master/ceph#2-osd-%E7%A3%81%E7%9B%98 这里操作来代替 disk zap 步骤
